---
abstract: 'Utilify functions for C<vmailmg.plr> administration tool.'
author:
  - 'Rogier Krieger <rkrieger@cpan.org>'
build_requires:
  IPC::System::Simple: 0
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: VMailMgr
provides:
  Qmail::VMailMgr:
    file: lib/Qmail/VMailMgr.pm
    version: 0.11
  Qmail::VMailMgr::Config:
    file: lib/Qmail/VMailMgr/Config.pm
requires:
  CDB_File: 0
  Config::INI::Reader: 0
  File::HomeDir: 0
  File::Temp: 0
  IO::File: 0
  Moose: 0
  MooseX::Configuration: 0
  Path::Class: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.11
